# Generated by Django 6.0.5 on 2026-06-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_education_experience_language_skill_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='level',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
